#!/usr/bin/env bash

for s in {1..10}; do
        for k in {1..10}; do
         python3 vd_pg.py --seed 0 --base_dir /data/amarildo/outputs2 --uniform --environment loop --objective pg --regularization cvar --alpha 0.1 --delta 0.9 --use_softmax --lr 0.1 --resample --reset_policy $
        done &
done
