#!/usr/bin/env bash
for s in {1..10}; do
    python3 vd_pg.py --seed 0 --environment chain --objective max --regularization lower_bound --alpha 0.1 --delta 0.9 --use_softmax --lr 0.1 --resample --reset_policy --max_iters 100 --iterations 50 --samples 100 --posterior_samples 1000 --lambda_ 0.01 &
done