#!/usr/bin/env bash
for s in {1..5}; do
    python3 vd_pg.py --seed 0 --environment 2_state --objective pg --regularization cvar --alpha 0.1 --delta 0.9 --use_softmax --lr 0.1 --resample --reset_policy --max_iters 100 --iterations 100 --samples 2000 --posterior_samples 100 --lambda_ 0. &
done