#!/usr/bin/env bash
for s in {1..10}; do
    for env in loop 2_state sixarms widenarrow
    do
      for lambda in 0.
      do
        python3 vd_pg.py --seed 0 --environment $env --objective max --regularization cvar --alpha 0.1 --delta 0.9 --use_softmax --lr 0.1 --resample --reset_policy --max_iters 100 --iterations 50 --samples 100 --posterior_samples 1000 --lambda_ $lambda
      done
    done &
done