#!/usr/bin/env bash

for s in {1..10}; do
    for alpha in 0.01 0.1 0.25
    do
      for lambda in 0.01 0.1
      do
        python3 vd_pg.py --seed 0 --environment chain --objective max --regularization lower_bound --alpha $alpha --delta 0.9 --use_softmax --lr 0.1 --resample --reset_policy --max_iters 100 --iterations 50 --samples 100 --posterior_samples 1000 --lambda_ $lambda
      done
    done &
done