env_type: self
env_setup: 
  _target_: envs.chain.Chain
  nState: 5
  prob_slip: 0.2
  discount: 0.99
  seed: ${seed}

env_id: chain
terminates: false
traj_len: 100

norm_reward: false

start_train_ep: 10
train_freq_ep: 1

start_train_step: 1000
train_freq_step: 100

