env_type: gym
env_setup:
  _target_: envs.cliffwalking.CliffWalkingEnv
  seed: ${seed}

env_id: CliffWalking-v0 #CliffWalking
terminates: true
traj_len: 100

norm_reward: false

start_train_ep: 10
train_freq_ep: 1

start_train_step: 1000
train_freq_step: 100


