env_type: self
env_setup: 
  _target_: envs.doubleloop.DoubleLoop
  seed: ${seed}

env_id: doubleloop
terminates: false
traj_len: 100

start_train_ep: 10
train_freq_ep: 1

start_train_step: 1000
train_freq_step: 100

