env_type: self
env_setup:
  _target_: envs.randomfrozenlake.RandomFrozenLakeEnv
  seed: ${seed}
  is_slippery: true
  map_name: null

env_id: FrozenLake4x4 #FrozenLake-v1 #
terminates: true
traj_len: 100

start_train_ep: 100
train_freq_ep: 10

start_train_step: 10000
train_freq_step: 1000

