env_type: self
env_setup: 
  _target_: envs.basic_envs.SimpleMDP
  epsilon: 0.05
  gamma: 0.99
  seed: ${seed}

env_id: twoState
terminates: false
traj_len: 100

norm_reward: false

start_train_ep: 10
train_freq_ep: 1

start_train_step: 1000
train_freq_step: 100

