defaults:
  - train_type: max-opt-cvar
  - env: SafetyGrid #CliffWalking #FrozenLake #
  - _self_

init_lambda: 1.0
reset_params: true 

optimization_type: constrained
alpha_baseline: 0.8

num_samples_plan: 500
num_eps_eval: 10
num_eps: 10000

risk_threshold: 0.1
k_value: 4
log_freq: 1
eps_rel: 0.1
significance_level: 0.1
temperature: 1
use_incorrect_priors: false

sigma: 'CVaR' #only for MC2PS
num_models: 10 #only for MC2PS
num_discounts: 10 #only for MC2PS

wandb_entity: 'rabachi'

seed: 0
hydra_dir_end: default

hydra:
  run:
    # dir: /scratch/gobi1/abachiro/small_mbrl_results/exp/${now:%Y-%m-%d}/${train_type.type}_${env.env_name}_cvarfirst
    #dir: /scratch/gobi1/abachiro/small_mbrl_results/exp/norm_reward4_${now:%Y-%m-%d}/
    #${now:%H-%M-%S}
    dir: outputs/
    #should add slurm job id