defaults:
  - train_type: pg-CE #upper-cvar-opt-cvar
  - env: SafetyGrid # #CliffWalking #FrozenLake #
  - _self_

  # env_name: chain
  #FrozenLake4x4
  # traj_len: 100

init_lambda: 1.0
reset_params: true #false

optimization_type: conservative
alpha_baseline: 0.8

num_samples_plan: 500
num_eps_eval: 10
num_eps: 10000

risk_threshold: 0.1
k_value: 4
log_freq: 1
eps_rel: 0.1
significance_level: 0.1
temperature: 1
use_incorrect_priors: false

sigma: 'CVaR' #only for MC2PS
num_models: 10 #only for MC2PS
num_discounts: 10 #only for MC2PS


seed: 0
hydra_dir_end: default

hydra:
  run:
    # dir: /scratch/gobi1/abachiro/small_mbrl_results/exp/${now:%Y-%m-%d}/${train_type.type}_${env.env_name}_cvarfirst
    dir: /scratch/gobi1/abachiro/small_mbrl_results/exp/normed_reward_high_lr_${now:%Y-%m-%d}/
    #${now:%H-%M-%S}
    #should add slurm job id