defaults:
  - train_type: max-opt-cvar
  - env: chain #SafetyGrid  #TwoState #CliffWalking #FrozenLake #chain #DoubleLoop
  - _self_

init_lambda: 0.
reset_params: true
optimization_type: constrained
alpha_baseline: 0.8
num_samples_plan: 100
num_eps_eval: 50
num_eps: 10000
risk_threshold: 0.1
k_value: 4
log_freq: 1
eps_rel: 0.1
significance_level: 0.1
temperature: 1
use_incorrect_priors: false
sigma: 'CVaR' #only for MC2PS
num_models: 10 #only for MC2PS
num_discounts: 10 #only for MC2PS
wandb_entity: 'alikmeta'
gamma: 0.99
seed: 0
hydra_dir_end: default
csv_log: true
exact: true
return_log_period: 1
enable_eval: false
log_inner_distributions: false
use_softmax: True
use_logistic: False
use_adam: true
const_lambda: true
exact_eval: true
compute_optimal: true
clip_bonus: true
upper_delta: 1.
constrain_lower_bound: false
hydra:
  run:
    # dir: /scratch/gobi1/abachiro/small_mbrl_results/exp/${now:%Y-%m-%d}/${train_type.type}_${env.env_name}_cvarfirst
    #dir: /scratch/gobi1/abachiro/small_mbrl_results/exp/norm_reward4_${now:%Y-%m-%d}/
    #${now:%H-%M-%S}
    dir: outputs/
    #should add slurm job id